dist: trusty
sudo: false
language: node_js
node_js:
- '10.16'
cache:
  directories:
  - "./node_modules"
branches:
  only:
  - master
install:
- npm install
script:
- npm run buildlib
deploy:
  provider: npm
  email: toilatung@icloud.com
  api_key:
    secure: VHBLRsh504pyT1bHitKt2EjFBdr3zGsGqdBbNMPtI5rtz6sEKI8tXdoePvLPlnFJ/APkDXhZRIzOa3edjxVwBRgtBSULOcaa+/WmZHJDLeZJBTbFWUahK1AhmUS94R52BmHolmZ8nIeheOMw8jYeUx1anfAHlUW4SXVrEwJMFPOAYS3fVRJQHn/bsVYvUb0gCef2GRC7ZbiDK7Wu5xvgSm5QfnI5NiFB1mGCGfkadxJ27I5TK0fr+eJEkxb3LcHPpnnrWVTZ/oC7nX9SqfjwNpEjdRMfEmeMgNa3ha3JmSVRsv++AW0OTWtk4PUloTSLdV/dC6tKI9NUMi/B+BYdTEt0dQfXHX8E8SUuZ8OVzQTh3WjLRmL7oZ+Di2Sh4o3HhXsq17S3sPrPUeGqZxFoYiwejYF9yb+wSOoUqGZNb3zU4LpkvDLPBg/eSSLlJ57ZyMRWPRqS6qZtEkbdXsrx2NdCfnDAN/sI1Cckzm6suZBs3hxShad2xq1R/x+tjLwFlcQ6sAiSvdRTJzu5Wzq1wF1nJplvyoDlrtRQC/DQ7m1p3ESqWsn0UkTcRTaS5l3F9+wcR7eT1tdjX/y2w3HsliYnXB9mn2uD6Clq6ziRP9P7qlg1rgJfxr1OQPDHNKo1cEoSG0KbXEWDtyPoePH7m5zfriw4wqTO6d52Vs/hsqA=
  local_dir: dist/ng-tlt
  on:
    branch: master
