version: 2
defaults: &defaults
  working_directory: ~/
  docker:
    - image: circleci/node:6.9.5
jobs:
  build:
    steps:
      - checkout
      - run: npm install
      - run: npm run buildlib
  deploy:
    - run:
      name: Authenticate with registry
      command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
    # - run:
    #   name: Directory
    #   command: cd dist/ng-tlt
    - run:
      name: Publish package
      command: npm publish
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - deploy:
          requires:
            - build
