version: 2
jobs:
  build:
    working_directory: ~/NG-TLT
    docker:
      - image: circleci/node:10.16.0
    steps:
      - checkout
      - run: npm install
      - run: npm run buildlib
  deploy:
    working_directory: ~/NG-TLT
    docker:
      - image: circleci/node:10.16.0
    steps:
      - attach_workspace:
          at: ~/NG-TLT/dist/ng-tlt
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=f7b8ae4f-95ce-496e-8e82-c5183ed071dc" > ~/NG-TLT/.npmrc
      - run:
        name: Publish
        command: npm publish
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy
