version: 2
jobs:
  build:
    working_directory: ~/NG-TLT
    docker:
      - image: circleci/node:10.16.0
    pre-steps:
      - run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
      - run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/NG-TLT/.npmrc
      - run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/NG-TLT/dist/ng-tlt/.npmrc
    steps:
      - checkout
      - run: less ~/.npmrc
      - run: npm install
      - run: npm run buildlib
      - run: cd dist/ng-tlt;npm publish
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
