name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    name: BUILD Library
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: Install NPM Package
        run: npm install
      - name: Build Library
        run: npm run buildlib
      - run: cd dist/ng-tlt
      - name: GitHub Action for npm
        uses: actions/npm@1.0.0
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_REGISTRY_URL: "http://registry.npmjs.org"
        with:
          args: publish
